name: aigc-3dgs-fusion
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pillow
  - tqdm
  - requests
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
